USE ROLE ACCOUNTADMIN;

CREATE DATABASE IF NOT EXISTS KAMESH_DEMO_DB;

USE DATABASE KAMESH_DEMO_DB;

CREATE SCHEMA IF NOT EXISTS DATA;

CREATE IF NOT EXISTS FILE FORMAT csv_ff
    SKIP_HEADER=1;

CREATE OR REPLACE TABLE TODOS (
    TITLE STRING,
    DESCRIPTION STRING,
    CATEGORY STRING,
    STATUS BOOLEAN,
)

COPY INTO TODOS FROM @git_integration_demo/branches/main/todos.csv